//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int client_id { get; set; }
        public string fio { get; set; }
        public int series { get; set; }
        public int number { get; set; }
        public System.DateTime birthday { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
