//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DEMOekzEntities : DbContext
    {
        public DEMOekzEntities()
            : base("name=DEMOekzEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<offer> offer { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<sys_enter> sys_enter { get; set; }
        public virtual DbSet<worker> worker { get; set; }
    }
}
