//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public System.DateTime create_data { get; set; }
        public System.TimeSpan create_time { get; set; }
        public int client_id { get; set; }
        public string offers { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public int offer_time { get; set; }
    }
}
