//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_enter
    {
        public int id { get; set; }
        public string position { get; set; }
        public string fullname { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public System.DateTime last_enter { get; set; }
        public string result { get; set; }
    }
}
