//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        public int worker_id { get; set; }
        public string position { get; set; }
        public string firstname { get; set; }
        public string secondname { get; set; }
        public string lastname { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    }
}
